/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.project;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

class SimpleTest {
    @Test
    void test1() {
        assertTrue(true);
    }

    @Test
    void test2() {
        assertFalse(true);
    }

    @Test
    void test3() throws InterruptedException {
        assertNotNull(new Object());
    }

    @Test
    void test4() {
        assertNotNull(null);
    }

    @Test
    void test5() {
        assertFalse(true);
    }

    @Test
    void test6() {
        assertFalse(true);
    }

    @Test
    void test7() {
        assertFalse(true);
    }

    @Test
    void test8() {
        assertFalse(true);
    }
}
